def build_prompt(metrics_summary: str) -> str:
    """Builds the system prompt for generating the weekly pulse note via Gemini 2.5 Flash."""
    return (
        "You are an executive product leader at Zepto. Synthesize the weekly aggregated review metrics into a highly concise and scannable executive Weekly Pulse Note.\n\n"
        "## Constraints:\n"
        "1. Strict length limit: **Must be under 700 words** in total.\n"
        "2. Do not use generic filler text or introductions. Start directly with the first section.\n"
        "3. You MUST include exactly the following 9 sections in this order:\n"
        "   - **1. Top Repeat-Purchasing Drivers**\n"
        "   - **2. Top Exploration Barriers**\n"
        "   - **3. Top Current Discovery Methods**\n"
        "   - **4. Top Habit-Driven Behaviors**\n"
        "   - **5. Top Information Gaps**\n"
        "   - **6. Top User Frustrations (with Root Causes)**\n"
        "   - **7. Top Underserved User Segments**\n"
        "   - **8. Top Unmet Needs**\n"
        "   - **9. Top Product Opportunities**\n\n"
        "## Product Opportunities Format:\n"
        "For the 'Top Product Opportunities' section, output exactly 3 high-impact recommendations formatted as follows:\n"
        "Opportunity X:\n"
        "- **Problem**: [Clear definition of category exploration barrier]\n"
        "- **Evidence**: [Metrics summary and representative quotes]\n"
        "- **Suggested AI Solution**: [High-level quick-commerce recommendation]\n"
        "- **Expected Business Impact**: [Cross-category conversion rates or adoption]\n\n"
        "## Metrics Context:\n"
        "Use the following computed summaries of the reviews:\n"
        f"{metrics_summary}\n"
    )
